### ISSUE TITLE
Support discovery without responding with HTML

### ISSUE THREAD

**Issue by gobengo** [w3c-social/activitypub#49] opened 2015-12-02 00:03 UTC
Webmention allows for discovering a webmention endpoint via Link response header.

I think ActivityPump should do the same.

I further think the spec should mention discovery via webfinger link relations so that domains can delegate activitypump to another provider without having to change their response handlers (e.g. to add HTML or Link headers)

also: https://hypothes.is/a/dBIUUgBnQpatN8RntwbQwA

**Comment by cwebber** [comment] 2016-03-16 14:27
It seems like this is a duplicate of #50 right?  Reopen if I'm wrong!

**Closed by cwebber** 2016-03-16 14:27 UTC
